name: trivy

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
  schedule:
    - cron: "0 20 * * *"
      timezone: "Europe/Warsaw"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6.0.3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL
